server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest-service-testing
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false